Update XQ.SZSE002 Set Market='SN',STK_CD=SYMBOL;
--Update XQ.SZSE002
--set Market=(select Market from XQ.SZSE001 WHERE XQ.SZSE002.STK_CD=XQ.SZSE001.STK_CD )
--where XQ.SZSE002.STK_CD in (select STK_CD from XQ.SZSE001  where STK_CD is not null);
commit;

MERGE INTO SW.FSK004 D
USING (select '00' as STKDATA_KIND,
SZSE002.STK_CD as STKLG_TYPE,
MARKET as DEAL_CTR,
to_char(tDate,'YYYYMMDD') as DATA_DATE,
NVL(tOpen,0)  as OPEN_PRI,
NVL(tClose,0)  as CLS_PRI,
NVL(tHigh,0)  as TOP_PRI,
NVL(tLow,0)  as LOW_PRI,
NVL(tVolume,0) as TRA_QTY, 
NVL(cast(tAmount as number(16)),0) as TRA_AMT,
NVL(cast(Capital as number(16)),0) as CPTL_AMT,
---NVL(cast(OS_STK as number(12)),0)*1000 as OS_STK,
'C' as TR_SOURCE,
'XQ' as UPD_USER,
to_char(SYSDATE,'YYYYMMDD') as UPD_DATE,
to_char(SYSDATE,'HHMISS') as UPD_TIME,
'XQ' as UPLOAD_UID,
to_char(SYSDATE,'YYYYMMDD') as UPLOAD_DATE,
to_char(SYSDATE,'HHMISS') as UPLOAD_TIME
from XQ.SZSE002
left join XQ.CN_CAPITAL on CN_CAPITAL.SYMBOL=SZSE002.SYMBOL
WHERE MARKET IS Not NULL and (LTRIM(XQ.SZSE002.SYMBOL,'0') in (SELECT fsk001.STK_CD from fsk001 where fsk001.DEAL_CTR='SN'))
) S
on (D.STKDATA_KIND = S.STKDATA_KIND AND D.DEAL_CTR=S.DEAL_CTR AND D.STKLG_TYPE=S.STKLG_TYPE AND D.DATA_DATE=S.DATA_DATE)
WHEN MATCHED THEN UPDATE SET 
D.OPEN_PRI = S.OPEN_PRI,
D.CLS_PRI = S.CLS_PRI,
D.TOP_PRI = S.TOP_PRI,
D.LOW_PRI = S.LOW_PRI,
D.TRA_QTY = S.TRA_QTY,
D.TRA_AMT = S.TRA_AMT,
D.CPTL_AMT = S.CPTL_AMT,
---D.OS_STK = S.OS_STK,
D.TR_SOURCE = S.TR_SOURCE,
D.UPD_USER = S.UPD_USER,
D.UPD_DATE = S.UPD_DATE,
D.UPD_TIME = S.UPD_TIME,
D.UPLOAD_UID = S.UPLOAD_UID,
D.UPLOAD_DATE = S.UPLOAD_DATE,
D.UPLOAD_TIME = S.UPLOAD_TIME
WHEN NOT MATCHED THEN INSERT 
(D.STKDATA_KIND,
D.STKLG_TYPE,
D.DEAL_CTR,
D.DATA_DATE,
D.OPEN_PRI,
D.CLS_PRI,
D.TOP_PRI,
D.LOW_PRI,
D.TRA_QTY,
D.TRA_AMT,
D.CPTL_AMT,
---D.OS_STK,
D.TR_SOURCE,
D.UPD_USER,
D.UPD_DATE,
D.UPD_TIME,
D.UPLOAD_UID,
D.UPLOAD_DATE,
D.UPLOAD_TIME)
VALUES 
(S.STKDATA_KIND,
S.STKLG_TYPE,
S.DEAL_CTR,
S.DATA_DATE,
S.OPEN_PRI,
S.CLS_PRI,
S.TOP_PRI,
S.LOW_PRI,
S.TRA_QTY,
S.TRA_AMT,
S.CPTL_AMT,
---S.OS_STK,
S.TR_SOURCE,
S.UPD_USER,
S.UPD_DATE,
S.UPD_TIME,
S.UPLOAD_UID,
S.UPLOAD_DATE,
S.UPLOAD_TIME);
commit;
exit;
