Merge INTO SW.FSK004 D
USING (
select '00' as STKDATA_KIND,
LTRIM(SYMBOL,'0')||' HK'  as STKLG_TYPE,
'H1' as DEAL_CTR,
to_char(tDate,'YYYYMMDD') as DATA_DATE,
NVL(tOpen,0) as OPEN_PRI,
NVL(tClose,0) as CLS_PRI,
NVL(tHigh,0) as TOP_PRI,
NVL(tLow,0) as LOW_PRI,
NVL(tVolume,0)  as TRA_QTY,
'C' as TR_SOURCE,
'XQ' as UPD_USER,
to_char(SYSDATE,'YYYYMMDD') as UPD_DATE,
to_char(SYSDATE,'HHMISS') as UPD_TIME,
'XQ' as UPLOAD_UID,
to_char(SYSDATE,'YYYYMMDD') as UPLOAD_DATE,
to_char(SYSDATE,'HHMISS') as UPLOAD_TIME
from XQ.HK002
WHERE LENGTH(SYMBOL)<7 AND SYMBOL!='HSI'
) S
on (D.STKDATA_KIND = S.STKDATA_KIND AND D.DEAL_CTR=S.DEAL_CTR AND D.STKLG_TYPE=S.STKLG_TYPE AND D.DATA_DATE=S.DATA_DATE)
WHEN MATCHED THEN UPDATE SET
D.OPEN_PRI = S.OPEN_PRI,
D.CLS_PRI = S.CLS_PRI,
D.TOP_PRI = S.TOP_PRI,
D.LOW_PRI = S.LOW_PRI,
D.TRA_QTY = S.TRA_QTY,
D.TR_SOURCE = S.TR_SOURCE,
D.UPD_USER = S.UPD_USER,
D.UPD_DATE = S.UPD_DATE,
D.UPD_TIME = S.UPD_TIME,
D.UPLOAD_UID = S.UPLOAD_UID,
D.UPLOAD_DATE = S.UPLOAD_DATE,
D.UPLOAD_TIME = S.UPLOAD_TIME
WHEN NOT MATCHED THEN INSERT
(D.STKDATA_KIND,
D.STKLG_TYPE,
D.DEAL_CTR,
D.DATA_DATE,
D.OPEN_PRI,
D.CLS_PRI,
D.TOP_PRI,
D.LOW_PRI,
D.TRA_QTY,
D.TR_SOURCE,
D.UPD_USER,
D.UPD_DATE,
D.UPD_TIME,
D.UPLOAD_UID,
D.UPLOAD_DATE,
D.UPLOAD_TIME)
VALUES
(S.STKDATA_KIND,
S.STKLG_TYPE,
S.DEAL_CTR,
S.DATA_DATE,
S.OPEN_PRI,
S.CLS_PRI,
S.TOP_PRI,
S.LOW_PRI,
S.TRA_QTY,
S.TR_SOURCE,
S.UPD_USER,
S.UPD_DATE,
S.UPD_TIME,
S.UPLOAD_UID,
S.UPLOAD_DATE,
S.UPLOAD_TIME);
commit;

Merge INTO SW.FSK004 D
USING (
select '40' as STKDATA_KIND,
'00000000' as STKLG_TYPE,
'H1' as DEAL_CTR,
to_char(tDate,'YYYYMMDD') as DATA_DATE,
tOpen as OPEN_PRI,
tClose as CLS_PRI,
tHigh as TOP_PRI,
tLow as LOW_PRI,
tVolume as TRA_QTY,
'C' as TR_SOURCE,
'XQ' as UPD_USER,
to_char(SYSDATE,'YYYYMMDD') as UPD_DATE,
to_char(SYSDATE,'HHMISS') as UPD_TIME,
'XQ' as UPLOAD_UID,
to_char(SYSDATE,'YYYYMMDD') as UPLOAD_DATE,
to_char(SYSDATE,'HHMISS') as UPLOAD_TIME
from XQ.HK002
WHERE LENGTH(SYMBOL)<7 and SYMBOL='HSI'
) S
on (D.STKDATA_KIND = S.STKDATA_KIND AND D.DEAL_CTR=S.DEAL_CTR AND D.STKLG_TYPE=S.STKLG_TYPE AND D.DATA_DATE=S.DATA_DATE)
WHEN MATCHED THEN UPDATE SET
D.OPEN_PRI = S.OPEN_PRI,
D.CLS_PRI = S.CLS_PRI,
D.TOP_PRI = S.TOP_PRI,
D.LOW_PRI = S.LOW_PRI,
D.TRA_QTY = S.TRA_QTY,
D.TR_SOURCE = S.TR_SOURCE,
D.UPD_USER = S.UPD_USER,
D.UPD_DATE = S.UPD_DATE,
D.UPD_TIME = S.UPD_TIME,
D.UPLOAD_UID = S.UPLOAD_UID,
D.UPLOAD_DATE = S.UPLOAD_DATE,
D.UPLOAD_TIME = S.UPLOAD_TIME
WHEN NOT MATCHED THEN INSERT
(D.STKDATA_KIND,
D.STKLG_TYPE,
D.DEAL_CTR,
D.DATA_DATE,
D.OPEN_PRI,
D.CLS_PRI,
D.TOP_PRI,
D.LOW_PRI,
D.TRA_QTY,
D.TR_SOURCE,
D.UPD_USER,
D.UPD_DATE,
D.UPD_TIME,
D.UPLOAD_UID,
D.UPLOAD_DATE,
D.UPLOAD_TIME)
VALUES
(S.STKDATA_KIND,
S.STKLG_TYPE,
S.DEAL_CTR,
S.DATA_DATE,
S.OPEN_PRI,
S.CLS_PRI,
S.TOP_PRI,
S.LOW_PRI,
S.TRA_QTY,
S.TR_SOURCE,
S.UPD_USER,
S.UPD_DATE,
S.UPD_TIME,
S.UPLOAD_UID,
S.UPLOAD_DATE,
S.UPLOAD_TIME);
commit;
exit;
              

