Update XQ.WFD002 WFD002
set (CO_ID,CO_FUND_ID,CRNCY_CD)=
(select RSIT.CO_ID,RSIT.CO_FUND_ID,CRNCY_CD
from (select CO_ID,CO_FUND_ID,SYMBOL from SW.fgl039 
left join (select SYMBOL,UNICODE from XQ.WFD001)  XQ on (XQ.UNICODE=ISIN_CODE ))RSIT
WHERE WFD002.SYMBOL=RSIT.SYMBOL);
commit;

Update XQ.FD002 FD002
set (CO_ID,CO_FUND_ID,CRNCY_CD)=
(select RSIT.CO_ID,RSIT.CO_FUND_ID,CRNCY_CD
from (select CO_ID,CO_FUND_ID,SYMBOL from SW.fgl039 
left join (select SYMBOL,ISIN from XQ.FD001)  XQ on (XQ.ISIN=UNI_CD ))RSIT
WHERE FD002.SYMBOL=RSIT.SYMBOL);
commit;

MERGE INTO SW.fsk085 D
   USING (SELECT CO_ID,CO_FUND_ID,TNAV,to_char(TDATE,'YYYYMMDD') as CONAV_DATE,CRNCY_CD from XQ.FD002 where CO_ID is not null AND 
   SYMBOL not in (SELECT SYMBOL from XQ.FD001 WHERE  ISIN in (select ISIN from (select count(*) as num,ISIN from XQ.FD001 group by ISIN) where num> 1))) S
   ON (D.CO_ID = S.CO_ID AND D.CO_FUND_ID=S.CO_FUND_ID AND D.CONAV_DATE=S.CONAV_DATE)
   WHEN MATCHED THEN UPDATE SET D.TR_SOUC='C',D.CRNCY_CD=S.CRNCY_CD,D.DATA_DATE=S.CONAV_DATE,D.DEAL_CTR='T2',D.DL_UPD_USER='XQ',D.DL_UPD_DATE=to_char(SYSDATE,'YYYYMMDD'),D.DL_UPD_TIME=to_char(SYSDATE,'HHMMSS'),D.CONAV=S.TNAV
   WHEN NOT MATCHED THEN INSERT (D.TR_SOUC,D.CRNCY_CD,D.CO_ID,D.CO_FUND_ID,D.DL_UPD_USER,D.DL_UPD_DATE,D.DL_UPD_TIME,D.CONAV_DATE,D.CONAV,D.DATA_DATE,D.DEAL_CTR)  VALUES ('C',S.CRNCY_CD,S.CO_ID,S.CO_FUND_ID,'XQ',to_char(SYSDATE,'YYYYMMDD'),to_char(SYSDATE,'HHMMSS'),S.CONAV_DATE,S.TNAV,S.CONAV_DATE,'T2');

Commit;

MERGE INTO SW.fsk085 D
   USING (SELECT CO_ID,CO_FUND_ID,TNAV,to_char(TDATE,'YYYYMMDD') as CONAV_DATE,CRNCY_CD from XQ.WFD002 where CO_ID is not null AND
   SYMBOL not in (SELECT SYMBOL from XQ.WFD001 WHERE UNICODE in  (select UNICODE from (select count(*) as num,UNICODE from XQ.WFD001 group by UNICODE) where num> 1))) S
   ON (D.CO_ID = S.CO_ID AND D.CO_FUND_ID=S.CO_FUND_ID AND D.CONAV_DATE=S.CONAV_DATE)
   WHEN MATCHED THEN UPDATE SET D.TR_SOUC='C',D.CRNCY_CD=S.CRNCY_CD,D.DATA_DATE=S.CONAV_DATE,D.DEAL_CTR='U1',D.DL_UPD_USER='XQ',D.DL_UPD_DATE=to_char(SYSDATE,'YYYYMMDD'),D.DL_UPD_TIME=to_char(SYSDATE,'HHMMSS'),D.CONAV=S.TNAV
   WHEN NOT MATCHED THEN INSERT (D.TR_SOUC,D.CRNCY_CD,D.CO_ID,D.CO_FUND_ID,D.DL_UPD_USER,D.DL_UPD_DATE,D.DL_UPD_TIME,D.CONAV_DATE,D.CONAV,D.DATA_DATE,D.DEAL_CTR)  VALUES ('C',S.CRNCY_CD,S.CO_ID,S.CO_FUND_ID,'XQ',to_char(SYSDATE,'YYYYMMDD'),to_char(SYSDATE,'HHMMSS'),S.CONAV_DATE,S.TNAV,S.CONAV_DATE,'U2');


Commit;
exit;
