MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'ACT003',F24 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='ACT003')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F24
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'ACT003',S.F24);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'ACT003',F24 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='ACT003')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F24
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'ACT003',S.F24);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'ACT004',F25 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='ACT004')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F25
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'ACT004',S.F25);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'ACT004',F25 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='ACT004')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F25
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'ACT004',S.F25);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'ACT009',F26 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='ACT009')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F26
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'ACT009',S.F26);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'ACT009',F26 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='ACT009')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F26
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'ACT009',S.F26);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'ACT010',F28 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='ACT010')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F28
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'ACT010',S.F28);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'ACT010',F28 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='ACT010')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F28
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'ACT010',S.F28);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'ACT014',F12 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='ACT014')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F12
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'ACT014',S.F12);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'ACT014',F12 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='ACT014')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F12
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'ACT014',S.F12);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'MKT001',F7 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='MKT001')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F7
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'MKT001',S.F7);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'MKT001',F7 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='MKT001')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F7
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'MKT001',S.F7);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'MKT002',F5 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='MKT002')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F5
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'MKT002',S.F5);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'MKT002',F5 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='MKT002')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F5
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'MKT002',S.F5);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'MKT009',F6 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='MKT009')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F6
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'MKT009',S.F6);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'MKT009',F6 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='MKT009')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F6
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'MKT009',S.F6);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'SRF003',F19 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='SRF003')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F19
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'SRF003',S.F19);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'SRF003',F19 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='SRF003')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F19
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'SRF003',S.F19);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'SRF008',F23 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='SRF008')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F23
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'SRF008',S.F23);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'SRF008',F23 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='SRF008')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F23
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'SRF008',S.F23);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'SRF008',F23 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='SRF008')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F23
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'SRF008',S.F23);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'SRF008',F23 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='SRF008')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F23
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'SRF008',S.F23);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'STR002',F21 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='STR002')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F21
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'STR002',S.F21);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'STR002',F21 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='STR002')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F21
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'STR002',S.F21);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'YLD001',F1 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='YLD001')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F1
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'YLD001',S.F1);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'YLD001',F1 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='YLD001')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F1
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'YLD001',S.F1);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'YLD002',F2 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='YLD002')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F2
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'YLD002',S.F2);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'YLD002',F2 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='YLD002')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F2
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'YLD002',S.F2);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'YLD015',F9 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='YLD015')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F9
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'YLD015',S.F9);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'YLD015',F9 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='YLD015')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F9
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'YLD015',S.F9);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'YLD016',F19 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='YLD016')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F19
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'YLD016',S.F19);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'YLD016',F19 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='YLD016')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F19
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'YLD016',S.F19);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'XQSP01',F3 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP01')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F3
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP01',S.F3);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'XQSP01',F3 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP01')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F3
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP01',S.F3);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'XQSP02',F4 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP02')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F4
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP02',S.F4);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'XQSP02',F4 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP02')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F4
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP02',S.F4);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'XQSP03',F8 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP03')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F8
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP03',S.F8);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'XQSP03',F8 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP03')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F8
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP03',S.F8);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'XQSP04',F11 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP04')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F11
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP04',S.F11);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'XQSP04',F11 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP04')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F11
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP04',S.F11);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'XQSP05',F13 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP05')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F13
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP05',S.F13);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'XQSP05',F13 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP05')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F13
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP05',S.F13);
   
Commit;


MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'XQSP06',F14 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP06')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F14
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP06',S.F14);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'XQSP06',F14 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP06')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F14
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP06',S.F14);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'XQSP07',F15 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP07')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F15
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP07',S.F15);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'XQSP07',F15 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP07')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F15
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP07',S.F15);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'XQSP08',F16 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP08')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F16
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP08',S.F16);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'XQSP08',F16 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP08')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F16
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP08',S.F16);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'XQSP09',F17 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP09')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F17
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP09',S.F17);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'XQSP09',F17 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP09')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F17
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP09',S.F17);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'XQSP10',F18 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP10')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F18
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP10',S.F18);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'XQSP10',F18 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP10')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F18
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP10',S.F18);
   
Commit;


MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'XQSP11',F22 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP11')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F22
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP11',S.F22);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'XQSP11',F22 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP11')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F22
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP11',S.F22);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'XQSP12',F27 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP12')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F27
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP12',S.F27);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'XQSP12',F27 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP12')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F27
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP12',S.F27);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'XQSP13',F29 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP13')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F29
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP13',S.F29);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'XQSP13',F29 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP13')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F29
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP13',S.F29);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'XQSP14',F30 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP14')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F30
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP14',S.F30);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select (LTRIM(SYMBOL,'0')||' HK') as SYMBOL, YQ,'XQSP14',F30 from XQ.FIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year')) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP14')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F30
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP14',S.F30);
   
Commit;

exit;
