Update XQ.TW_Dividend Set Market=(select Market from XQ.TW001 where XQ.TW001.SYMBOL=XQ.TW_Dividend.STOCKID);
commit;
--- 除權 除息
MERGE INTO SW.FSK013 D
   USING (select STOCKID as STK_CD, NVL(MARKET,'T4') as DEAL_CTR,TO_CHAR(IDATE,'YYYYMMDD') as DIV_PUR_DT,'NTD' as CRNCY_CD,ICASH as CDPS_AMT,0 as RE_RTO,ADIV as CS_RTO,NVL(NEW_CAP,0) as RI_STK_RTO,NVL(UW_PRICE,0) as RIPS_COST,'Y' as EX_STK_YN,TO_CHAR(NEW_CAP_DATE,'YYYYMMDD') as RCV_STK_DT,'XQ' as UPD_USER,0 as TAX_RTO,to_char(SYSDATE,'YYYYMMDD') as UPD_DATE,to_char(SYSDATE,'HHMISS') as UPD_TIME from XQ.TW_Dividend where IDATE is not null and DDATE is null) S
        ON (D.STK_CD = S.STK_CD and D.DIV_PUR_DT=S.DIV_PUR_DT )
   WHEN MATCHED THEN UPDATE SET
           D.CRNCY_CD=S.CRNCY_CD,
           D.CDPS_AMT=S.CDPS_AMT,
           D.RE_RTO=S.RE_RTO*10,
           D.CS_RTO=S.CS_RTO*10,
           D.RI_STK_RTO=S.RI_STK_RTO,
           D.RIPS_COST=S.RIPS_COST,
           D.EX_STK_YN=S.EX_STK_YN,
           D.RCV_STK_DT=S.RCV_STK_DT,
           D.UPD_USER=S.UPD_USER,
           D.TAX_RTO=S.TAX_RTO,
           D.UPD_DATE=S.UPD_DATE,
           D.UPD_TIME=S.UPD_TIME
 WHEN NOT MATCHED THEN     INSERT      (D.STK_CD,D.DEAL_CTR,D.DIV_PUR_DT,D.CRNCY_CD,D.CDPS_AMT,   D.RE_RTO   ,D.CS_RTO,   D.RI_STK_RTO,D.RIPS_COST,D.EX_STK_YN,D.RCV_STK_DT,D.UPD_USER,D.TAX_RTO,D.UPD_DATE,D.UPD_TIME)
   VALUES (S.STK_CD,S.DEAL_CTR,S.DIV_PUR_DT,S.CRNCY_CD,S.CDPS_AMT,S.RE_RTO*10,S.CS_RTO*10,S.RI_STK_RTO,S.RIPS_COST,S.EX_STK_YN,S.RCV_STK_DT,S.UPD_USER,S.TAX_RTO,S.UPD_DATE,S.UPD_TIME);
commit;
MERGE INTO SW.FSK013 D
   USING (select STOCKID as STK_CD, NVL(MARKET,'T4') as DEAL_CTR,TO_CHAR(DDATE,'YYYYMMDD') as DIV_PUR_DT,'NTD' as CRNCY_CD,0 as CDPS_AMT,NVL(PDIV,0) as RE_RTO,ADIV as CS_RTO,NVL(NEW_CAP,0) as RI_STK_RTO,NVL(UW_PRICE,0) as RIPS_COST,'Y' as EX_STK_YN,TO_CHAR(NEW_CAP_DATE,'YYYYMMDD') as RCV_STK_DT,'XQ' as UPD_USER,0 as TAX_RTO,to_char(SYSDATE,'YYYYMMDD') as UPD_DATE,to_char(SYSDATE,'HHMISS') as UPD_TIME from XQ.TW_Dividend where DDATE is not null and IDATE is null) S
        ON (D.STK_CD = S.STK_CD and D.DIV_PUR_DT=S.DIV_PUR_DT )
   WHEN MATCHED THEN UPDATE SET
           D.CRNCY_CD=S.CRNCY_CD,
           D.CDPS_AMT=S.CDPS_AMT,
           D.RE_RTO=S.RE_RTO*10,
           D.CS_RTO=S.CS_RTO*10,
           D.RI_STK_RTO=S.RI_STK_RTO,
           D.RIPS_COST=S.RIPS_COST,
           D.EX_STK_YN=S.EX_STK_YN,
           D.RCV_STK_DT=S.RCV_STK_DT,
           D.UPD_USER=S.UPD_USER,
           D.TAX_RTO=S.TAX_RTO,
           D.UPD_DATE=S.UPD_DATE,
		   D.UPD_TIME=S.UPD_TIME
 WHEN NOT MATCHED THEN     INSERT      (D.STK_CD,D.DEAL_CTR,D.DIV_PUR_DT,D.CRNCY_CD,D.CDPS_AMT,   D.RE_RTO   ,D.CS_RTO,   D.RI_STK_RTO,D.RIPS_COST,D.EX_STK_YN,D.RCV_STK_DT,D.UPD_USER,D.TAX_RTO,D.UPD_DATE,D.UPD_TIME)
  VALUES (S.STK_CD,S.DEAL_CTR,S.DIV_PUR_DT,S.CRNCY_CD,S.CDPS_AMT,S.RE_RTO*10,S.CS_RTO*10,S.RI_STK_RTO,S.RIPS_COST,S.EX_STK_YN,S.RCV_STK_DT,S.UPD_USER,S.TAX_RTO,S.UPD_DATE,S.UPD_TIME);
commit;
MERGE INTO SW.FSK013 D
   USING (select STOCKID as STK_CD, NVL(MARKET,'T4') as DEAL_CTR,TO_CHAR(IDATE,'YYYYMMDD') as DIV_PUR_DT,'NTD' as CRNCY_CD,ICASH as CDPS_AMT,NVL(PDIV,0) as RE_RTO,ADIV as CS_RTO,NVL(NEW_CAP,0) as RI_STK_RTO,NVL(UW_PRICE,0) as RIPS_COST,'Y' as EX_STK_YN,TO_CHAR(NEW_CAP_DATE,'YYYYMMDD') as RCV_STK_DT,'XQ' as UPD_USER,0 as TAX_RTO,to_char(SYSDATE,'YYYYMMDD') as UPD_DATE,to_char(SYSDATE,'HHMISS') as UPD_TIME from XQ.TW_Dividend where IDATE is not null and DDATE is not null) S
        ON (D.STK_CD = S.STK_CD and D.DIV_PUR_DT=S.DIV_PUR_DT )
   WHEN MATCHED THEN UPDATE SET
           D.CRNCY_CD=S.CRNCY_CD,
           D.CDPS_AMT=S.CDPS_AMT,
           D.RE_RTO=S.RE_RTO*10,
           D.CS_RTO=S.CS_RTO*10,
           D.RI_STK_RTO=S.RI_STK_RTO,
           D.RIPS_COST=S.RIPS_COST,
           D.EX_STK_YN=S.EX_STK_YN,
           D.RCV_STK_DT=S.RCV_STK_DT,
           D.UPD_USER=S.UPD_USER,
           D.TAX_RTO=S.TAX_RTO,
           D.UPD_DATE=S.UPD_DATE,
           D.UPD_TIME=S.UPD_TIME
 WHEN NOT MATCHED THEN     INSERT      (D.STK_CD,D.DEAL_CTR,D.DIV_PUR_DT,D.CRNCY_CD,D.CDPS_AMT,   D.RE_RTO   ,D.CS_RTO,   D.RI_STK_RTO,D.RIPS_COST,D.EX_STK_YN,D.RCV_STK_DT,D.UPD_USER,D.TAX_RTO,D.UPD_DATE,D.UPD_TIME)
   VALUES (S.STK_CD,S.DEAL_CTR,S.DIV_PUR_DT,S.CRNCY_CD,S.CDPS_AMT,S.RE_RTO*10,S.CS_RTO*10,S.RI_STK_RTO,S.RIPS_COST,S.EX_STK_YN,S.RCV_STK_DT,S.UPD_USER,S.TAX_RTO,S.UPD_DATE,S.UPD_TIME);
commit;
Update SW.FSK013
set LSBY_DATE=get_bsdt_num(DIV_PUR_DT,'01','2',3),LSRG_DATE=get_bsdt_num(DIV_PUR_DT,'01','2',1)
where UPD_USER='XQ';
commit;
exit;

