Update XQ.US001 Set Market='US',STK_CD=TRIM(SYMBOL),STK_CHNM=cast(SUBSTR(Name,0,20) as varchar(20)),STK_ENGNM=cast(SUBSTR(SEName,0,50) as varchar(50));
Update XQ.US002 Set Market='US',STK_CD=TRIM(SYMBOL),tVolume=COALESCE(TO_NUMBER(REGEXP_SUBSTR(tVolume_STR, '^\d+(\.\d+)?')), 0);
Update XQ.US001 Set Market='US',STK_CD=TRIM(SYMBOL),STK_CHNM=cast(SUBSTR(Name,0,20) as varchar(20)),STK_ENGNM=cast(SUBSTR(SEName,0,50) as varchar(50));
Update XQ.US002 Set Market='US',STK_CD=TRIM(SYMBOL),tVolume=COALESCE(TO_NUMBER(REGEXP_SUBSTR(tVolume_STR, '^\d+(\.\d+)?')), 0);

Update XQ.US001
set Market=(select DEAL_CTR from SW.fsk001 WHERE SW.fsk001.STK_CD=LTRIM(XQ.US001.STK_CD,'0')||' US' and SW.fsk001.DEAL_CTR in ('U2','U1'));
commit;

Update XQ.US002
set Market=(select DEAL_CTR from SW.fsk001 WHERE SW.fsk001.STK_CD=LTRIM(XQ.US002.STK_CD,'0')||' US' and SW.fsk001.DEAL_CTR in ('U2','U1'));
commit;
MERGE INTO SW.FSK004 D
   USING (select '00' as STKDATA_KIND,LTRIM(SYMBOL,'0')||' US' as STKLG_TYPE,Market as DEAL_CTR,to_char(tDate,'YYYYMMDD') as DATA_DATE,
NVL(tOpen,0) as OPEN_PRI,
NVL(tClose,0) as CLS_PRI,
NVL(tHigh,0) as TOP_PRI,
NVL(tLow,0) as LOW_PRI,
NVL(tVolume,0) as TRA_QTY,
'C' as TR_SOURCE,'XQ' as UPD_USER,to_char(SYSDATE,'YYYYMMDD') as UPD_DATE,to_char(SYSDATE,'HHMISS') as UPD_TIME,
   'XQ' as UPLOAD_UID,to_char(SYSDATE,'YYYYMMDD') as UPLOAD_DATE,to_char(SYSDATE,'HHMISS') as UPLOAD_TIME from XQ.US002 where length(Symbol)<=7 and ((LTRIM(SYMBOL,'0')||' US') in (SELECT fsk001.STK_CD from fsk001))
) S
   ON (D.STKDATA_KIND=S.STKDATA_KIND AND D.DEAL_CTR=S.DEAL_CTR AND D.STKLG_TYPE = S.STKLG_TYPE AND D.DATA_DATE=S.DATA_DATE)
   WHEN MATCHED THEN UPDATE 
   SET 
	D.OPEN_PRI=S.OPEN_PRI,
	D.CLS_PRI=S.CLS_PRI,
	D.TOP_PRI=S.TOP_PRI,
	D.LOW_PRI=S.LOW_PRI,
	D.TRA_QTY=S.TRA_QTY,
	D.TR_SOURCE=S.TR_SOURCE,
	D.UPD_USER=S.UPD_USER,
	D.UPD_DATE=S.UPD_DATE,
	D.UPD_TIME=S.UPD_TIME,
	D.UPLOAD_UID=S.UPLOAD_UID,
	D.UPLOAD_DATE=S.UPLOAD_DATE,
	D.UPLOAD_TIME=S.UPLOAD_TIME
   WHEN NOT MATCHED THEN INSERT (
	D.STKDATA_KIND,
	D.STKLG_TYPE,
	D.DEAL_CTR,
	D.DATA_DATE,
	D.OPEN_PRI,
	D.CLS_PRI,
	D.TOP_PRI,
	D.LOW_PRI,
	D.TRA_QTY,
	D.TR_SOURCE,
	D.UPD_USER,
	D.UPD_DATE,
	D.UPD_TIME,
	D.UPLOAD_UID,
	D.UPLOAD_DATE,
	D.UPLOAD_TIME)  
	VALUES (
	S.STKDATA_KIND,
	S.STKLG_TYPE,
	S.DEAL_CTR,
	S.DATA_DATE,
	S.OPEN_PRI,
	S.CLS_PRI,
	S.TOP_PRI,
	S.LOW_PRI,
	S.TRA_QTY,
	S.TR_SOURCE,
	S.UPD_USER,
	S.UPD_DATE,
	S.UPD_TIME,
	S.UPLOAD_UID,
	S.UPLOAD_DATE,
	S.UPLOAD_TIME);

commit;
exit;
