MERGE INTO XQ.TWFIN001 D
   USING (select SYMBOL, FINDATE,YEARDATE,ANNDATE,F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,F11,F12,F13,F14,F15,F16,F17,F18,F19,F20,F21,F22,F23,F24,F25,F26,F27,F28,F29,F30,STK_CD,YQ from XQ.TWFIN001B where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') ) S
   ON (D.SYMBOL = S.SYMBOL AND D.YQ=S.YQ AND D.FINDATE=S.FINDATE)
   WHEN MATCHED THEN UPDATE SET 
   D.F1 = case when (NVL(D.F1,0)=0 and NVL(D.F2,0)=0 and NVL(D.F3,0)=0 and NVL(D.F4,0)=0 and NVL(D.F5,0)=0 and NVL(D.F6,0)=0 and NVL(D.F7,0)=0 and NVL(D.F8,0)=0 and NVL(D.F9,0)=0) then S.F1 else D.F1 end,
   D.F2 = case when (NVL(D.F1,0)=0 and NVL(D.F2,0)=0 and NVL(D.F3,0)=0 and NVL(D.F4,0)=0 and NVL(D.F5,0)=0 and NVL(D.F6,0)=0 and NVL(D.F7,0)=0 and NVL(D.F8,0)=0 and NVL(D.F9,0)=0) then S.F2 else D.F2 end,
   D.F3 = case when (NVL(D.F1,0)=0 and NVL(D.F2,0)=0 and NVL(D.F3,0)=0 and NVL(D.F4,0)=0 and NVL(D.F5,0)=0 and NVL(D.F6,0)=0 and NVL(D.F7,0)=0 and NVL(D.F8,0)=0 and NVL(D.F9,0)=0) then S.F3 else D.F3 end,
   D.F4 = case when (NVL(D.F1,0)=0 and NVL(D.F2,0)=0 and NVL(D.F3,0)=0 and NVL(D.F4,0)=0 and NVL(D.F5,0)=0 and NVL(D.F6,0)=0 and NVL(D.F7,0)=0 and NVL(D.F8,0)=0 and NVL(D.F9,0)=0) then S.F4 else D.F4 end,
   D.F5 = case when (NVL(D.F1,0)=0 and NVL(D.F2,0)=0 and NVL(D.F3,0)=0 and NVL(D.F4,0)=0 and NVL(D.F5,0)=0 and NVL(D.F6,0)=0 and NVL(D.F7,0)=0 and NVL(D.F8,0)=0 and NVL(D.F9,0)=0) then S.F5 else D.F5 end,
   D.F6 = case when (NVL(D.F1,0)=0 and NVL(D.F2,0)=0 and NVL(D.F3,0)=0 and NVL(D.F4,0)=0 and NVL(D.F5,0)=0 and NVL(D.F6,0)=0 and NVL(D.F7,0)=0 and NVL(D.F8,0)=0 and NVL(D.F9,0)=0) then S.F6 else D.F6 end,
   D.F7 = case when (NVL(D.F1,0)=0 and NVL(D.F2,0)=0 and NVL(D.F3,0)=0 and NVL(D.F4,0)=0 and NVL(D.F5,0)=0 and NVL(D.F6,0)=0 and NVL(D.F7,0)=0 and NVL(D.F8,0)=0 and NVL(D.F9,0)=0) then S.F7 else D.F7 end,
   D.F8 = case when (NVL(D.F1,0)=0 and NVL(D.F2,0)=0 and NVL(D.F3,0)=0 and NVL(D.F4,0)=0 and NVL(D.F5,0)=0 and NVL(D.F6,0)=0 and NVL(D.F7,0)=0 and NVL(D.F8,0)=0 and NVL(D.F9,0)=0) then S.F8 else D.F8 end,
   D.F9 = case when (NVL(D.F1,0)=0 and NVL(D.F2,0)=0 and NVL(D.F3,0)=0 and NVL(D.F4,0)=0 and NVL(D.F5,0)=0 and NVL(D.F6,0)=0 and NVL(D.F7,0)=0 and NVL(D.F8,0)=0 and NVL(D.F9,0)=0) then S.F9 else D.F9 end,
   D.F10 = case when (NVL(D.F1,0)=0 and NVL(D.F2,0)=0 and NVL(D.F3,0)=0 and NVL(D.F4,0)=0 and NVL(D.F5,0)=0 and NVL(D.F6,0)=0 and NVL(D.F7,0)=0 and NVL(D.F8,0)=0 and NVL(D.F9,0)=0) then S.F10 else D.F10 end,
   D.F11 = case when (NVL(D.F1,0)=0 and NVL(D.F2,0)=0 and NVL(D.F3,0)=0 and NVL(D.F4,0)=0 and NVL(D.F5,0)=0 and NVL(D.F6,0)=0 and NVL(D.F7,0)=0 and NVL(D.F8,0)=0 and NVL(D.F9,0)=0) then S.F11 else D.F11 end,
   D.F12 = case when (NVL(D.F1,0)=0 and NVL(D.F2,0)=0 and NVL(D.F3,0)=0 and NVL(D.F4,0)=0 and NVL(D.F5,0)=0 and NVL(D.F6,0)=0 and NVL(D.F7,0)=0 and NVL(D.F8,0)=0 and NVL(D.F9,0)=0) then S.F12 else D.F12 end,
   D.F13 = case when (NVL(D.F1,0)=0 and NVL(D.F2,0)=0 and NVL(D.F3,0)=0 and NVL(D.F4,0)=0 and NVL(D.F5,0)=0 and NVL(D.F6,0)=0 and NVL(D.F7,0)=0 and NVL(D.F8,0)=0 and NVL(D.F9,0)=0) then S.F13 else D.F13 end,
   D.F14 = case when (NVL(D.F1,0)=0 and NVL(D.F2,0)=0 and NVL(D.F3,0)=0 and NVL(D.F4,0)=0 and NVL(D.F5,0)=0 and NVL(D.F6,0)=0 and NVL(D.F7,0)=0 and NVL(D.F8,0)=0 and NVL(D.F9,0)=0) then S.F14 else D.F14 end,
   D.F15 = case when (NVL(D.F1,0)=0 and NVL(D.F2,0)=0 and NVL(D.F3,0)=0 and NVL(D.F4,0)=0 and NVL(D.F5,0)=0 and NVL(D.F6,0)=0 and NVL(D.F7,0)=0 and NVL(D.F8,0)=0 and NVL(D.F9,0)=0) then S.F15 else D.F15 end,
   D.F16 = case when (NVL(D.F1,0)=0 and NVL(D.F2,0)=0 and NVL(D.F3,0)=0 and NVL(D.F4,0)=0 and NVL(D.F5,0)=0 and NVL(D.F6,0)=0 and NVL(D.F7,0)=0 and NVL(D.F8,0)=0 and NVL(D.F9,0)=0) then S.F16 else D.F16 end,
   D.F17 = case when (NVL(D.F1,0)=0 and NVL(D.F2,0)=0 and NVL(D.F3,0)=0 and NVL(D.F4,0)=0 and NVL(D.F5,0)=0 and NVL(D.F6,0)=0 and NVL(D.F7,0)=0 and NVL(D.F8,0)=0 and NVL(D.F9,0)=0) then S.F17 else D.F17 end,
   D.F18 = case when (NVL(D.F1,0)=0 and NVL(D.F2,0)=0 and NVL(D.F3,0)=0 and NVL(D.F4,0)=0 and NVL(D.F5,0)=0 and NVL(D.F6,0)=0 and NVL(D.F7,0)=0 and NVL(D.F8,0)=0 and NVL(D.F9,0)=0) then S.F18 else D.F18 end,
   D.F19 = case when (NVL(D.F1,0)=0 and NVL(D.F2,0)=0 and NVL(D.F3,0)=0 and NVL(D.F4,0)=0 and NVL(D.F5,0)=0 and NVL(D.F6,0)=0 and NVL(D.F7,0)=0 and NVL(D.F8,0)=0 and NVL(D.F9,0)=0) then S.F19 else D.F19 end,
   D.F20 = case when (NVL(D.F1,0)=0 and NVL(D.F2,0)=0 and NVL(D.F3,0)=0 and NVL(D.F4,0)=0 and NVL(D.F5,0)=0 and NVL(D.F6,0)=0 and NVL(D.F7,0)=0 and NVL(D.F8,0)=0 and NVL(D.F9,0)=0) then S.F20 else D.F20 end,
   D.F21 = case when (NVL(D.F1,0)=0 and NVL(D.F2,0)=0 and NVL(D.F3,0)=0 and NVL(D.F4,0)=0 and NVL(D.F5,0)=0 and NVL(D.F6,0)=0 and NVL(D.F7,0)=0 and NVL(D.F8,0)=0 and NVL(D.F9,0)=0) then S.F21 else D.F21 end,
   D.F22 = case when (NVL(D.F1,0)=0 and NVL(D.F2,0)=0 and NVL(D.F3,0)=0 and NVL(D.F4,0)=0 and NVL(D.F5,0)=0 and NVL(D.F6,0)=0 and NVL(D.F7,0)=0 and NVL(D.F8,0)=0 and NVL(D.F9,0)=0) then S.F22 else D.F22 end,
   D.F23 = case when (NVL(D.F1,0)=0 and NVL(D.F2,0)=0 and NVL(D.F3,0)=0 and NVL(D.F4,0)=0 and NVL(D.F5,0)=0 and NVL(D.F6,0)=0 and NVL(D.F7,0)=0 and NVL(D.F8,0)=0 and NVL(D.F9,0)=0) then S.F23 else D.F23 end,
   D.F24 = case when (NVL(D.F1,0)=0 and NVL(D.F2,0)=0 and NVL(D.F3,0)=0 and NVL(D.F4,0)=0 and NVL(D.F5,0)=0 and NVL(D.F6,0)=0 and NVL(D.F7,0)=0 and NVL(D.F8,0)=0 and NVL(D.F9,0)=0) then S.F24 else D.F24 end,
   D.F25 = case when (NVL(D.F1,0)=0 and NVL(D.F2,0)=0 and NVL(D.F3,0)=0 and NVL(D.F4,0)=0 and NVL(D.F5,0)=0 and NVL(D.F6,0)=0 and NVL(D.F7,0)=0 and NVL(D.F8,0)=0 and NVL(D.F9,0)=0) then S.F25 else D.F25 end,
   D.F26 = case when (NVL(D.F1,0)=0 and NVL(D.F2,0)=0 and NVL(D.F3,0)=0 and NVL(D.F4,0)=0 and NVL(D.F5,0)=0 and NVL(D.F6,0)=0 and NVL(D.F7,0)=0 and NVL(D.F8,0)=0 and NVL(D.F9,0)=0) then S.F26 else D.F26 end,
   D.F27 = case when (NVL(D.F1,0)=0 and NVL(D.F2,0)=0 and NVL(D.F3,0)=0 and NVL(D.F4,0)=0 and NVL(D.F5,0)=0 and NVL(D.F6,0)=0 and NVL(D.F7,0)=0 and NVL(D.F8,0)=0 and NVL(D.F9,0)=0) then S.F27 else D.F27 end,
   D.F28 = case when (NVL(D.F1,0)=0 and NVL(D.F2,0)=0 and NVL(D.F3,0)=0 and NVL(D.F4,0)=0 and NVL(D.F5,0)=0 and NVL(D.F6,0)=0 and NVL(D.F7,0)=0 and NVL(D.F8,0)=0 and NVL(D.F9,0)=0) then S.F28 else D.F28 end,
   D.F29 = case when (NVL(D.F1,0)=0 and NVL(D.F2,0)=0 and NVL(D.F3,0)=0 and NVL(D.F4,0)=0 and NVL(D.F5,0)=0 and NVL(D.F6,0)=0 and NVL(D.F7,0)=0 and NVL(D.F8,0)=0 and NVL(D.F9,0)=0) then S.F29 else D.F29 end,
   D.F30 = case when (NVL(D.F1,0)=0 and NVL(D.F2,0)=0 and NVL(D.F3,0)=0 and NVL(D.F4,0)=0 and NVL(D.F5,0)=0 and NVL(D.F6,0)=0 and NVL(D.F7,0)=0 and NVL(D.F8,0)=0 and NVL(D.F9,0)=0) then S.F30 else D.F30 end
   WHEN NOT MATCHED THEN INSERT (D.SYMBOL, D.FINDATE,D.YEARDATE,D.ANNDATE,D.F1,D.F2,D.F3,D.F4,D.F5,D.F6,D.F7,D.F8,D.F9,D.F10,D.F11,D.F12,D.F13,D.F14,D.F15,D.F16,D.F17,D.F18,D.F19,D.F20,D.F21,D.F22,D.F23,D.F24,D.F25,D.F26,D.F27,D.F28,D.F29,D.F30,D.STK_CD,D.YQ)  
   VALUES (S.SYMBOL, S.FINDATE,S.YEARDATE,S.ANNDATE,S.F1,S.F2,S.F3,S.F4,S.F5,S.F6,S.F7,S.F8,S.F9,S.F10,S.F11,S.F12,S.F13,S.F14,S.F15,S.F16,S.F17,S.F18,S.F19,S.F20,S.F21,S.F22,S.F23,S.F24,S.F25,S.F26,S.F27,S.F28,S.F29,S.F30,S.STK_CD,S.YQ);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'ACT003',F24 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='ACT003')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F24
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'ACT003',S.F24);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'ACT003',F24 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='ACT003')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F24
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'ACT003',S.F24);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'ACT004',F25 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='ACT004')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F25
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'ACT004',S.F25);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'ACT004',F25 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='ACT004')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F25
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'ACT004',S.F25);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'ACT009',F26 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='ACT009')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F26
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'ACT009',S.F26);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'ACT009',F26 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='ACT009')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F26
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'ACT009',S.F26);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'ACT010',F28 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='ACT010')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F28
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'ACT010',S.F28);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'ACT010',F28 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='ACT010')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F28
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'ACT010',S.F28);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'ACT014',F12 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='ACT014')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F12
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'ACT014',S.F12);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'ACT014',F12 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='ACT014')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F12
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'ACT014',S.F12);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'MKT001',F7 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='MKT001')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F7
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'MKT001',S.F7);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'MKT001',F7 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='MKT001')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F7
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'MKT001',S.F7);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'MKT002',F5 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='MKT002')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F5
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'MKT002',S.F5);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'MKT002',F5 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='MKT002')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F5
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'MKT002',S.F5);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'MKT009',F6 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='MKT009')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F6
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'MKT009',S.F6);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'MKT009',F6 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='MKT009')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F6
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'MKT009',S.F6);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'SRF003',F19 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='SRF003')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F19
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'SRF003',S.F19);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'SRF003',F19 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='SRF003')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F19
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'SRF003',S.F19);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'SRF008',F23 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='SRF008')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F23
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'SRF008',S.F23);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'SRF008',F23 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='SRF008')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F23
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'SRF008',S.F23);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'SRF008',F23 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='SRF008')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F23
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'SRF008',S.F23);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'SRF008',F23 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='SRF008')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F23
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'SRF008',S.F23);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'STR002',F21 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='STR002')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F21
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'STR002',S.F21);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'STR002',F21 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='STR002')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F21
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'STR002',S.F21);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'YLD001',F1 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='YLD001')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F1
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'YLD001',S.F1);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'YLD001',F1 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='YLD001')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F1
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'YLD001',S.F1);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'YLD002',F2 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='YLD002')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F2
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'YLD002',S.F2);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'YLD002',F2 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='YLD002')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F2
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'YLD002',S.F2);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'YLD015',F9 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='YLD015')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F9
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'YLD015',S.F9);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'YLD015',F9 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='YLD015')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F9
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'YLD015',S.F9);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'YLD016',F19 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='YLD016')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F19
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'YLD016',S.F19);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'YLD016',F19 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='YLD016')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F19
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'YLD016',S.F19);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'XQSP01',F3 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP01')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F3
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP01',S.F3);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'XQSP01',F3 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP01')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F3
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP01',S.F3);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'XQSP02',F4 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP02')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F4
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP02',S.F4);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'XQSP02',F4 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP02')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F4
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP02',S.F4);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'XQSP03',F8 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP03')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F8
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP03',S.F8);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'XQSP03',F8 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP03')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F8
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP03',S.F8);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'XQSP04',F11 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP04')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F11
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP04',S.F11);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'XQSP04',F11 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP04')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F11
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP04',S.F11);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'XQSP05',F13 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP05')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F13
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP05',S.F13);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'XQSP05',F13 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP05')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F13
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP05',S.F13);
   
Commit;


MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'XQSP06',F14 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP06')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F14
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP06',S.F14);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'XQSP06',F14 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP06')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F14
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP06',S.F14);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'XQSP07',F15 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP07')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F15
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP07',S.F15);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'XQSP07',F15 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP07')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F15
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP07',S.F15);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'XQSP08',F16 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP08')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F16
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP08',S.F16);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'XQSP08',F16 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP08')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F16
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP08',S.F16);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'XQSP09',F17 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP09')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F17
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP09',S.F17);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'XQSP09',F17 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP09')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F17
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP09',S.F17);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'XQSP10',F18 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP10')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F18
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP10',S.F18);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'XQSP10',F18 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP10')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F18
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP10',S.F18);
   
Commit;


MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'XQSP11',F22 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP11')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F22
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP11',S.F22);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'XQSP11',F22 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP11')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F22
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP11',S.F22);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'XQSP12',F27 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP12')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F27
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP12',S.F27);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'XQSP12',F27 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP12')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F27
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP12',S.F27);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'XQSP13',F29 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP13')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F29
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP13',S.F29);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'XQSP13',F29 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP13')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F29
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP13',S.F29);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'XQSP14',F30 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP14')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F30
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP14',S.F30);
   
Commit;

MERGE INTO SW.RAT001 D
   USING (select SYMBOL, YQ,'XQSP14',F30 from XQ.TWFIN001 where FinDate>TRUNC(TRUNC(SYSDATE , 'Year')-360 , 'Year') and NVL(YQ,0)<>0) S
   ON (D.LIST_CODE = S.SYMBOL AND D.YQ=S.YQ AND D.RATIO_CODE='XQSP14')
   WHEN MATCHED THEN UPDATE SET D.RATIO_VALUE = S.F30
   WHEN NOT MATCHED THEN INSERT (D.LIST_CODE,D.YQ,D.RATIO_CODE,D.RATIO_VALUE)  VALUES (S.SYMBOL, S.YQ,'XQSP14',S.F30);
   
Commit;

exit;

